import { z } from 'zod'

const shape = {
  uid: z.number(),
  payslip_id: z.number(),
  employer_name: z.string().nullable(),
  comment: z.string().nullable().optional(),
  start_date: z.date(),
  end_date: z.date(),
  pay_date: z.date(),
  gross_earnings: z.number().default(0),
  net_pay: z.number().default(0),
  net_pay_ytd: z.number().default(0),
  gross_earnings_ytd: z.number().default(0),
  state_additional_tax: z.number().default(0),
  federal_additional_tax: z.number().default(0),
  imp_ltd_period: z.number().default(0),
  imp_ltd_ytd: z.number().default(0),
  life_choice_period: z.number().default(0),
  life_choice_ytd: z.number().default(0),
  restricted_stock_units_period: z.number().default(0),
  restricted_stock_units_ytd: z.number().default(0),
  salary_period: z.number().default(0),
  salary_ytd: z.number().default(0),
  totalhrswrkd_period: z.number().default(0),
  totalhrswrkd_ytd: z.number().default(0),
  '401k_salary_period': z.number().default(0),
  '401k_salary_ytd': z.number().default(0),
  pretax_medical_period: z.number().default(0),
  pretax_medical_ytd: z.number().default(0),
  medical_fsa_period: z.number().default(0),
  medical_fsa_ytd: z.number().default(0),
  after_tax_401k_salary_period: z.number().default(0),
  after_tax_401k_salary_ytd: z.number().default(0),
  rsu_excess_refund_period: z.number().default(0),
  rsu_excess_refund_ytd: z.number().default(0),
  rsu_tax_offset_period: z.number().default(0),
  rsu_tax_offset_ytd: z.number().default(0),
  oasdi_period: z.number().default(0),
  oasdi_ytd: z.number().default(0),
  medicare_period: z.number().default(0),
  medicare_ytd: z.number().default(0),
  federal_withholding_period: z.number().default(0),
  federal_withholding_ytd: z.number().default(0),
  state_tax_period: z.number().default(0),
  state_tax_ytd: z.number().default(0),
  vdi_period: z.number().default(0),
  vdi_ytd: z.number().default(0),
  state_tax_state: z.string().optional().nullable(),
}

export const Cols: { [key: string]: { title: string } } = {
  pay_date: { title: 'Date' },
  comment: { title: 'Comment' },
  bonus: { title: 'Bonus' },
  salary_period: { title: 'Salary' },
  rsu: { title: 'RSU' },
  oasdi_period: { title: 'OASDI' },
  medicare_period: { title: 'Medicare' },
  federal_withholding_period: { title: 'Fed Tax' },
  state_tax_period: { title: 'State Tax' },
  '401k_salary_period': { title: '401k pretax' },
  rsu_tax_offset_period: { title: 'RSU tax offset' },
  rsu_excess_refund_period: { title: 'RSU tax refunded' },
}

export const ZodPayslip = z.object(shape)
