export const ExpenseCategories = [
  'Advertising',
  'Car and truck',
  'Commissions and fees',
  'Contract labor',
  'Depletion',
  'Depreciation',
  'Employee benefit',
  'Insurance other than health',
  'Interest: Mortgage',
  'Interest: Other',
  'Legal and Professional',
  'Office Expense',
  'Pension and Profit Sharing',
  'Rent or lease',
  'Rent or lease: Vehicles',
  'Rent or lease: Property',
  'Repairs and maintenance',
  'Supplies',
  'Taxes and licenses',
  'Travel',
  'Meals 50%',
  'Meals 100%',
  'Utilities',
  'Wages',
  'Other',
  'Tuition',
  'Energy Efficient Commercial Buildings',
]
