/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Decimal = ColumnType<string, number | string>

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S, I | undefined, U> : ColumnType<T, T | undefined, T>

export interface Account {
  access_token: Generated<string | null>
  createdAt: Generated<string>
  expires_at: Generated<number | null>
  id: string
  id_token: Generated<string | null>
  provider: string
  providerAccountId: string
  refresh_token: Generated<string | null>
  refresh_token_expires_in: Generated<number | null>
  scope: Generated<string | null>
  session_state: Generated<string | null>
  token_type: Generated<string | null>
  type: string
  updatedAt: string
  userId: string
}

export interface AccountLineItems {
  /**
   * Option expiration date
   */
  opt_expiration: Generated<string | null>
  /**
   * Option strike price
   */
  opt_strike: Generated<Decimal>
  /**
   * Option type (call or put)
   */
  opt_type: Generated<'call' | 'put' | null>
  /**
   * Parent transaction id (for tracking transaction flow)
   */
  parent_t_id: Generated<number | null>
  /**
   * Account ID#
   */
  t_account: Generated<number | null>
  /**
   * Transaction total amount
   */
  t_amt: Generated<Decimal>
  /**
   * User-provided comment
   */
  t_comment: Generated<string | null>
  /**
   * Commission charged
   */
  t_commission: Generated<Decimal>
  t_cusip: Generated<string | null>
  /**
   * Date of transaction
   */
  t_date: string
  /**
   * Additional description text from the transaction log
   */
  t_description: Generated<string | null>
  /**
   * Fee charged
   */
  t_fee: Generated<Decimal>
  /**
   * Start date
   */
  t_from: Generated<string | null>
  /**
   * Transaction ID#
   */
  t_id: Generated<number>
  /**
   * Interest rate
   */
  t_interest_rate: Generated<string | null>
  /**
   * Method of accounting
   */
  t_method: Generated<string | null>
  t_origin: Generated<string | null>
  /**
   * Equity unit price
   */
  t_price: Generated<Decimal>
  /**
   * Quantity of options or shares
   */
  t_qty: Generated<number>
  t_schc_category: Generated<
    | 'Advertising'
    | 'Car and truck'
    | 'Commissions and fees'
    | 'Contract labor'
    | 'Depletion'
    | 'Depreciation'
    | 'Employee benefit'
    | 'Energy Efficient Commercial Buildings'
    | 'Insurance other than health'
    | 'Interest: Mortgage'
    | 'Interest: Other'
    | 'Legal and Professional'
    | 'Meals 0%'
    | 'Meals 100%'
    | 'Meals 50%'
    | 'Office Expense'
    | 'Other'
    | 'Pension and Profit Sharing'
    | 'Rent or lease'
    | 'Rent or lease: Property'
    | 'Rent or lease: Vehicles'
    | 'Repairs and maintenance'
    | 'Supplies'
    | 'Taxes and licenses'
    | 'Travel'
    | 'Tuition'
    | 'Utilities'
    | 'Wages'
    | null
  >
  t_source: Generated<string | null>
  /**
   * Stock symbol
   */
  t_symbol: Generated<string | null>
  /**
   * End date
   */
  t_to: Generated<string | null>
  /**
   * Type of transaction
   */
  t_type: Generated<
    | 'bought to cover'
    | 'bought to open'
    | 'credit'
    | 'deposit'
    | 'dividend'
    | 'equity'
    | 'interest'
    | 'journal'
    | 'option expiration'
    | 'refund'
    | 'sold short'
    | 'sold to close'
    | 'spend'
    | 'transfer'
    | null
  >
  when_added: Generated<string | null>
  when_deleted: Generated<string | null>
}

export interface Accounts {
  acct_id: Generated<number>
  acct_name: string
  acct_owner: Generated<number>
  acct_type: Generated<'brokerage' | 'general'>
  when_deleted: Generated<string | null>
}

export interface AccountSpend {
  account_id: number
  is_business: Generated<number>
  notes: Generated<string | null>
  spend_amount: Decimal
  spend_category: Generated<string | null>
  spend_date: Generated<string | null>
  spend_description: Generated<string | null>
  spend_id: Generated<number>
  t_schc_category: Generated<
    | 'Advertising'
    | 'Car and truck'
    | 'Commissions and fees'
    | 'Contract labor'
    | 'Depletion'
    | 'Depreciation'
    | 'Employee benefit'
    | 'Energy Efficient Commercial Buildings'
    | 'Insurance other than health'
    | 'Interest: Mortgage'
    | 'Interest: Other'
    | 'Legal and Professional'
    | 'Meals 0%'
    | 'Meals 100%'
    | 'Meals 50%'
    | 'Office Expense'
    | 'Other'
    | 'Pension and Profit Sharing'
    | 'Rent or lease'
    | 'Rent or lease: Property'
    | 'Rent or lease: Vehicles'
    | 'Repairs and maintenance'
    | 'Supplies'
    | 'Taxes and licenses'
    | 'Travel'
    | 'Tuition'
    | 'Utilities'
    | 'Wages'
    | null
  >
  transaction_type: Generated<string | null>
  when_added: Generated<string>
  when_deleted: Generated<string | null>
}

export interface Authenticator {
  counter: number
  credentialBackedUp: number
  credentialDeviceType: string
  credentialID: string
  credentialPublicKey: string
  providerAccountId: string
  transports: Generated<string | null>
  userId: string
}

export interface CarCms {
  dealer_city: Generated<string | null>
  dealer_name: Generated<string | null>
  dealer_phone: Generated<string | null>
  dealer_state: Generated<string | null>
  dealer_zip: Generated<string | null>
  id: Generated<number>
}

export interface CarPicker {
  battery_kwh: Generated<Decimal | null>
  brand: Generated<string | null>
  class: Generated<string | null>
  comments: Generated<string | null>
  date_unveiled: Generated<string | null>
  discontinued_date: Generated<string | null>
  ev_range_mi: Generated<number | null>
  ev_type: Generated<string | null>
  expected_release: Generated<string | null>
  global_msrp: Generated<string | null>
  ice_range_mi: Generated<number | null>
  l2_mcr: Generated<number | null>
  market_availability: Generated<string | null>
  max_dcfc: Generated<number | null>
  mfr_country: Generated<string | null>
  model_name: Generated<string | null>
  model_trim: Generated<string | null>
  model_year: Generated<string | null>
  motor_kw: Generated<number | null>
  motors: Generated<string | null>
  powertrain: Generated<string | null>
  release_date: Generated<string | null>
  seating: Generated<string | null>
  source: Generated<string | null>
  style: Generated<string | null>
  us_msrp: Generated<number | null>
}

export interface EarningsAnnual {
  fiscalDateEnding: string
  reportedEPS: Generated<Decimal | null>
  symbol: string
}

export interface EarningsLatest {
  date: Generated<string | null>
  eps: Generated<number | null>
  eps_est: Generated<number | null>
  qtr: Generated<string | null>
  release_time: Generated<string | null>
  symbol: Generated<string | null>
}

export interface EarningsQuarterly {
  estimatedEPS: Generated<Decimal | null>
  fiscalDateEnding: string
  reportedDate: Generated<string | null>
  reportedEPS: Generated<Decimal | null>
  surprise: Generated<Decimal | null>
  surprisePercentage: Generated<Decimal | null>
  symbol: string
}

export interface EvDatabase {
  '$/kwh': Generated<string | null>
  '$/mi EVR': Generated<string | null>
  'Batt kWh': Generated<string | null>
  Brand: Generated<string | null>
  Class: Generated<string | null>
  'Comb. Range': Generated<string | null>
  Comments: Generated<string | null>
  'Date Unveiled': Generated<string | null>
  Discontinued: Generated<string | null>
  'EV Type': Generated<string | null>
  'EVR (km)': Generated<string | null>
  'EVR (mi)': Generated<number | null>
  'Expected Release': Generated<string | null>
  'Global MSRP': Generated<string | null>
  'ICER (mi)': Generated<string | null>
  'kWh/100mi': Generated<string | null>
  'L2 MCR': Generated<string | null>
  'Market Availability': Generated<string | null>
  'Max DCFC': Generated<string | null>
  'Mfr Country': Generated<string | null>
  'mi/kWh': Generated<string | null>
  'Model Name': Generated<string | null>
  'Model Year': Generated<number | null>
  'Motor (kW)': Generated<number | null>
  Motors: Generated<string | null>
  Planned: Generated<string | null>
  Powertrain: Generated<string | null>
  'Release Date': Generated<string | null>
  Released: Generated<string | null>
  Seating: Generated<string | null>
  Source: Generated<string | null>
  Style: Generated<string | null>
  Trim: Generated<string | null>
  'US MSRP': Generated<string | null>
  'Vehicle Name': Generated<string | null>
  'wh/mi': Generated<string | null>
  YoM: Generated<Decimal | null>
}

export interface FinEquityAwards {
  award_id: number
  grant_date: string
  id: Generated<number>
  share_count: number
  symbol: string
  uid: number
  vest_date: string
  vest_price: Generated<Decimal | null>
}

export interface FinPayslip {
  earnings_bonus: Generated<Decimal | null>
  earnings_gross: Generated<Decimal | null>
  earnings_net_pay: Generated<Decimal>
  earnings_rsu: Generated<Decimal | null>
  imp_fitness: Generated<Decimal | null>
  imp_legal: Generated<Decimal | null>
  imp_ltd: Generated<Decimal | null>
  imp_other: Generated<Decimal | null>
  other: Generated<string | null>
  pay_date: Generated<string | null>
  payslip_id: Generated<number>
  period_end: Generated<string | null>
  period_start: Generated<string | null>
  ps_401k_aftertax: Generated<Decimal | null>
  ps_401k_employer: Generated<Decimal | null>
  ps_401k_pretax: Generated<Decimal | null>
  ps_comment: Generated<string | null>
  ps_fed_tax: Generated<Decimal | null>
  ps_fed_tax_addl: Generated<Decimal | null>
  ps_fed_tax_refunded: Generated<Decimal | null>
  ps_is_estimated: Generated<number>
  ps_medicare: Generated<Decimal | null>
  ps_oasdi: Generated<Decimal | null>
  ps_payslip_file_hash: Generated<string | null>
  ps_pretax_dental: Generated<Decimal>
  ps_pretax_fsa: Generated<Decimal>
  ps_pretax_medical: Generated<Decimal>
  ps_pretax_vision: Generated<Decimal>
  ps_salary: Generated<Decimal>
  ps_state_disability: Generated<Decimal | null>
  ps_state_tax: Generated<Decimal | null>
  ps_state_tax_addl: Generated<Decimal | null>
  ps_vacation_payout: Generated<Decimal>
  uid: number
}

export interface FinPayslipUploads {
  file_hash: Generated<string | null>
  file_name: Generated<string | null>
  id: Generated<number>
  parsed_json: Generated<string | null>
}

export interface GraduatedTax {
  income_over: number
  rate: Decimal
  region: string
  type: Generated<'hoh' | 'mfj' | 'mfs' | 's'>
  verified: Generated<Buffer>
  year: number
}

export interface MlsData {
  apn: Generated<string | null>
  bathrooms: Generated<Decimal | null>
  bedrooms: Generated<number | null>
  buildingIdSHA: Generated<string | null>
  city: Generated<string | null>
  compassPropertyId: Generated<string | null>
  county: Generated<string | null>
  countyFipsCode: Generated<string | null>
  fullBathrooms: Generated<Decimal | null>
  geoId: Generated<string | null>
  hasAirConditioning: Generated<number | null>
  hasFireplace: Generated<number | null>
  hasPool: Generated<number | null>
  hasView: Generated<number | null>
  homeFactsJson: Generated<string | null>
  id: Generated<number>
  lastPrice: Generated<number | null>
  latitude: Generated<Decimal | null>
  listingIdSHA: Generated<string | null>
  localizedStatus: Generated<string | null>
  longitude: Generated<Decimal | null>
  lotSize: Generated<string | null>
  neighborhood: Generated<string | null>
  perSquareFoot: Generated<Decimal | null>
  prettyAddress: string
  squareFeet: Generated<number | null>
  state: Generated<string | null>
  status: Generated<number | null>
  stories: Generated<number | null>
  style: Generated<string | null>
  totalAboveGradeFinishedSqft: Generated<number | null>
  totalBathrooms: Generated<Decimal | null>
  totalFinishedSqft: Generated<number | null>
  yearBuilt: Generated<number | null>
  zip: Generated<string | null>
  zoning: Generated<string | null>
}

export interface MlsDataAssessor {
  additionsValue: Generated<number | null>
  dateUpdated: Generated<number | null>
  id: Generated<number>
  landValue: Generated<number | null>
  mls_data_id: number
  monthlyTax: Generated<string | null>
  previousValue: Generated<number | null>
  tax: Generated<string | null>
  taxYear: Generated<number | null>
  year: Generated<number | null>
}

export interface Photo {
  female: Generated<number | null>
  fullsize: Generated<string | null>
  id: Generated<number>
  male: Generated<number | null>
  reported: Generated<number | null>
  thumb: Generated<string | null>
  views: Generated<number | null>
}

export interface PhrLabResults {
  analyte: Generated<string | null>
  collection_datetime: Generated<string | null>
  id: Generated<number>
  lab_director: Generated<string | null>
  message_from_provider: Generated<string | null>
  /**
   * Value is normal if it equals this e.g. "Not Detected"
   */
  normal_value: Generated<string | null>
  ordering_provider: Generated<string | null>
  /**
   * Value (unit) should be less than or equal to this value
   */
  range_max: Generated<Decimal | null>
  /**
   * Value (unit) should be greater than or equal to this value
   */
  range_min: Generated<Decimal | null>
  /**
   * Unit of range_min and range_max
   */
  range_unit: Generated<string | null>
  result_comment: Generated<string | null>
  result_datetime: Generated<string | null>
  result_status: Generated<string | null>
  resulting_lab: Generated<string | null>
  test_name: Generated<string | null>
  unit: Generated<string | null>
  /**
   * FK to users.id, the logged in user
   */
  user_id: Generated<number | null>
  value: Generated<string | null>
}

export interface PhrPatientVitals {
  id: Generated<number>
  user_id: Generated<number | null>
  vital_date: Generated<string | null>
  vital_name: Generated<string | null>
  vital_value: Generated<string | null>
}

export interface ProductKeys {
  claimed_date: Generated<string | null>
  comment: Generated<string | null>
  computer_name: Generated<string | null>
  id: Generated<number>
  key_retrieval_note: Generated<string | null>
  key_type: Generated<string | null>
  product_id: Generated<string | null>
  product_key: Generated<string | null>
  product_name: Generated<string | null>
  uid: Generated<number | null>
  used_on: Generated<string | null>
}

export interface Session {
  createdAt: Generated<string>
  expires: string
  id: string
  sessionToken: string
  updatedAt: string
  userId: string
}

export interface SpgpPasstypes {
  display_name: Generated<string | null>
  expiry: Generated<string | null>
  info: Generated<string | null>
  passtype_id: Generated<number>
}

export interface SpgpPromocodes {
  /**
   * the request id from spgp_requests
   */
  assignee_r_id: Generated<number | null>
  id: Generated<number>
  passtype_id: number
  rdmp_code: string
}

export interface SpgpRequests {
  deleted: Generated<number>
  passtype_id: Generated<number | null>
  r_birthdate: Generated<string | null>
  r_comment: Generated<string | null>
  r_email: string
  r_first: string
  r_id: Generated<number>
  r_last: string
  r_previous_passid: Generated<string | null>
  r_redeemedMonth: Generated<string | null>
  r_total: Generated<Decimal | null>
  r_used_on: Generated<string | null>
  uid: Generated<number | null>
}

export interface StockQuotes {
  c_close: Decimal
  c_date: string
  c_high: Decimal
  c_low: Decimal
  c_open: Decimal
  c_symb: string
  c_time: string
  c_vol: number
}

export interface StockQuotesDaily {
  c_close: Decimal
  c_date: string
  c_high: Decimal
  c_low: Decimal
  c_open: Decimal
  c_symb: string
  c_vol: number
}

export interface TimeseriesDatapoint {
  dp_comment: Generated<string | null>
  dp_date: Generated<string | null>
  dp_id: Generated<number>
  dp_series_id: number
  dp_value: Generated<string | null>
}

export interface TimeseriesDocuments {
  id: Generated<number>
  name: string
  uid: number
}

export interface TimeseriesSeries {
  document_id: number
  id: Generated<number>
  series_name: string
}

export interface User {
  createdAt: Generated<string>
  email: Generated<string | null>
  emailVerified: Generated<string | null>
  id: string
  image: Generated<string | null>
  name: Generated<string | null>
  updatedAt: string
  username: Generated<string | null>
}

export interface Users {
  alias: Generated<string | null>
  ax_evdb: Generated<number | null>
  ax_homes: Generated<number | null>
  ax_maxmin: Generated<number>
  ax_phr: Generated<number>
  ax_spgp: Generated<number>
  ax_tax: Generated<number>
  email: string
  passkey_credential_id: Generated<string | null>
  passkey_public_key: Generated<string | null>
  pw: Generated<string | null>
  reset_requested_at: Generated<string | null>
  reset_token: Generated<string | null>
  salt: Generated<number>
  uid: Generated<number>
}

export interface VerificationToken {
  expires: string
  identifier: string
  token: string
}

export interface VxcvFiles {
  blocked: Generated<number>
  downloads: Generated<number>
  filename: string
  hash: Buffer
  ip: number
  max_downloads: Generated<number>
  mime: string
  size: number
  uploaded: string
}

export interface VxcvLinks {
  uniqueid: string
  url: string
}

export interface WebauthnChallenges {
  challenge: string
  created_at: Generated<string>
  user_id: Generated<number | null>
}

export interface Words {
  word: string
}

export interface DB {
  Account: Account
  account_line_items: AccountLineItems
  account_spend: AccountSpend
  accounts: Accounts
  Authenticator: Authenticator
  car_cms: CarCms
  car_picker: CarPicker
  earnings_annual: EarningsAnnual
  earnings_latest: EarningsLatest
  earnings_quarterly: EarningsQuarterly
  ev_database: EvDatabase
  fin_equity_awards: FinEquityAwards
  fin_payslip: FinPayslip
  fin_payslip_uploads: FinPayslipUploads
  graduated_tax: GraduatedTax
  mls_data: MlsData
  mls_data_assessor: MlsDataAssessor
  photo: Photo
  phr_lab_results: PhrLabResults
  phr_patient_vitals: PhrPatientVitals
  product_keys: ProductKeys
  Session: Session
  spgp_passtypes: SpgpPasstypes
  spgp_promocodes: SpgpPromocodes
  spgp_requests: SpgpRequests
  stock_quotes: StockQuotes
  stock_quotes_daily: StockQuotesDaily
  timeseries_datapoint: TimeseriesDatapoint
  timeseries_documents: TimeseriesDocuments
  timeseries_series: TimeseriesSeries
  User: User
  users: Users
  VerificationToken: VerificationToken
  vxcv_files: VxcvFiles
  vxcv_links: VxcvLinks
  webauthn_challenges: WebauthnChallenges
  words: Words
}
